name: Power Platform CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (uat or prod)'
        required: true
        default: uat

permissions:
  contents: write

jobs:
  cd:
    uses: ./.github/workflows/powerapps-reusable.yml
    with:
      pp_url: ${{ github.event.inputs.environment == 'prod' && secrets.POWER_PLATFORM_PROD_URL || secrets.POWER_PLATFORM_UAT_URL }}
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      solutions: '["CoreSolution","DataverseSchemaSolution","FrontendAppSolution","AutomationSolution"]'
