name: Power Platform CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'uat'
        type: choice
        options:
          - uat
          - prod

permissions:
  contents: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          ENV_FILE="env/${{ github.event.inputs.environment }}.txt"
          if [ ! -f "$ENV_FILE" ]; then
            echo "Environment file $ENV_FILE not found!"
            exit 1
          fi
          set -o allexport
          source "$ENV_FILE"
          set +o allexport
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_ENV
          echo "SOLUTION_LIST=$SOLUTION_LIST" >> $GITHUB_ENV
          echo "DEPENDENCY_ORDER=$DEPENDENCY_ORDER" >> $GITHUB_ENV
          echo "POWER_PLATFORM_URL=$POWER_PLATFORM_URL" >> $GITHUB_ENV

      - name: Call reusable workflow
        uses: ./.github/workflows/powerapps-reusable.yml
        with:
          pp_url: ${{ env.POWER_PLATFORM_URL }}
          solutions: ${{ env.SOLUTION_LIST }}
        secrets:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
