name: Power Platform CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'uat'
        type: choice
        options:
          - uat
          - prod

permissions:
  contents: write

jobs:
  prepare:
    runs-on: self-hosted
    outputs:
      pp_url: ${{ steps.set-vars.outputs.pp_url }}
      solutions: ${{ steps.set-vars.outputs.solutions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment variables
        id: set-vars
        run: |
          ENV_FILE="env/${{ github.event.inputs.environment }}.txt"
          if [ ! -f "$ENV_FILE" ]; then
            echo "Environment file $ENV_FILE not found!"
            exit 1
          fi
          set -o allexport
          source "$ENV_FILE"
          set +o allexport
          echo "pp_url=$POWER_PLATFORM_URL" >> $GITHUB_OUTPUT
          echo "solutions=$SOLUTION_LIST" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    uses: Himaan1502/PowerApps-GitHubActions/.github/workflows/powerapps-reusable.yml@main
    with:
      pp_url: ${{ needs.prepare.outputs.pp_url }}
      solutions: ${{ needs.prepare.outputs.solutions }}
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
